name: mjcoffee
description: Project by majid Hajian

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.10.4 <3.0.0'
  flutter: '>=1.22.4 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.11.0
  flutter_svg: ^0.20.0-nullsafety.3
  http: ^0.13.0
  google_fonts: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Medium.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
